// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Routine.Test.Api
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Routine.Client;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class TestTemplate : TestTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nusing System;\r\n\r\n");
            
            #line 10 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 foreach(var model in Application.Models) { 
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 11 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 foreach(var mode in model.GetModes()) { 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 13 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetNamespace(mode)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\t");
            
            #line 15 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.RenderAttributes(mode)));
            
            #line default
            #line hidden
            this.Write("\r\n\tpublic class ");
            
            #line 16 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(mode)));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tprivate readonly ");
            
            #line 18 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeof(Robject).FullName));
            
            #line default
            #line hidden
            this.Write(" robject;\r\n\t\tpublic ");
            
            #line 19 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeof(Robject).FullName));
            
            #line default
            #line hidden
            this.Write(" Robject { get { return robject; } }\r\n\r\n\t\tpublic ");
            
            #line 21 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(mode)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 21 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeof(Robject).FullName));
            
            #line default
            #line hidden
            this.Write(" robject)\r\n\t\t{\r\n\t\t\tthis.robject = robject;\r\n\t\t}\r\n\t\t");
            
            #line 25 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 if(model.Initializable) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 27 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Initializer.RenderAttributes(mode)));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 28 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(mode)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 28 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", model.Initializer.Parameters.Select(p => p.ParameterModel.GetFullName(mode) + " " + p.GetName(mode)))));
            
            #line default
            #line hidden
            this.Write(") { }\r\n\t\t");
            
            #line 29 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 30 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 foreach(var member in model.Members) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 32 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.RenderAttributes(mode)));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 33 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnModel.GetFullName(mode)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 33 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.GetName(mode)));
            
            #line default
            #line hidden
            this.Write(" { get { return default(");
            
            #line 33 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnModel.GetFullName(mode)));
            
            #line default
            #line hidden
            this.Write("); } }\r\n\t\t");
            
            #line 34 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 35 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 foreach(var operation in model.Operations) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 37 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.RenderAttributes(mode)));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 38 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ReturnModel.GetFullName(mode)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 38 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.GetName(mode)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 38 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", operation.Parameters.Select(p => p.RenderAttributes(mode) + " " + p.ParameterModel.GetFullName(mode) + " " + p.GetName(mode)))));
            
            #line default
            #line hidden
            this.Write(") \r\n\t\t{\r\n\t\t\tvar __result = Robject.Perform\r\n\t\t\t\t(\r\n\t\t\t\t\"");
            
            #line 42 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Id));
            
            #line default
            #line hidden
            this.Write("\"\r\n\t\t\t");
            
            #line 43 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 foreach(var parameter in operation.Parameters) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t, ");
            
            #line 45 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.ParameterModel.RenderObjectToRvariable(mode, parameter.Id, parameter.GetName(mode), "robject.Application")));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 46 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\r\n\t\t\t\t)\r\n\t\t\t;\r\n\t\t\t");
            
            #line 50 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 if(!operation.ReturnModel.IsVoid) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\treturn ");
            
            #line 52 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ReturnModel.RenderRvariableToObject(mode, "__result", "robject.Application")));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t");
            
            #line 53 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t}\r\n\t\t");
            
            #line 56 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 58 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 foreach(var viewModel in model.ViewModels.Where(vm => vm.HasMode(mode))) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 60 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewModel.GetFullName(mode)));
            
            #line default
            #line hidden
            this.Write(" As");
            
            #line 60 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewModel.GetName(mode)));
            
            #line default
            #line hidden
            this.Write("()\r\n\t\t{\r\n\t\t\tvar __result = robject.As(robject.Application[\"");
            
            #line 62 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewModel.Id));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\treturn ");
            
            #line 63 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewModel.RenderRobjectToObject(mode, "__result", "robject.Application")));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t}\r\n        ");
            
            #line 65 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 67 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 foreach(var actualModel in model.ActualModels.Where(vm => vm.HasMode(mode))) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic bool Is");
            
            #line 69 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(actualModel.GetName(mode)));
            
            #line default
            #line hidden
            this.Write("()\r\n\t\t{\r\n\t\t\treturn robject.ActualType.Id == \"");
            
            #line 71 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(actualModel.Id));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\t}\r\n        ");
            
            #line 73 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic override string ToString()\r\n\t\t{\r\n\t\t\treturn robject.Id;\r\n\t\t}\r\n\t}\r\n}\r\n\t");
            
            #line 81 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 82 "D:\Projects\routine\routine\Routine.Test\Api\TestTemplate.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class TestTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
