// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Routine.Api.Template.T4
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;
    using Routine.Client;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class ClientApi : ClientApiBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nusing System.Linq;\r\n\r\n");
            
            #line 10 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 foreach(var assemblyName in Application.FriendlyAssemblyNames) { 
            
            #line default
            #line hidden
            this.Write("[assembly:");
            
            #line 11 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<InternalsVisibleToAttribute>()));
            
            #line default
            #line hidden
            this.Write("(\"");
            
            #line 11 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(assemblyName));
            
            #line default
            #line hidden
            this.Write("\")]\r\n");
            
            #line 12 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 15 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 if(Application.ApiExists) { 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 17 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Application.DefaultNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic class ");
            
            #line 19 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Application.ApiName));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tprivate readonly ");
            
            #line 21 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Rapplication>()));
            
            #line default
            #line hidden
            this.Write(" rapplication;\r\n\r\n\t\tpublic ");
            
            #line 23 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Application.ApiName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 23 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Rapplication>()));
            
            #line default
            #line hidden
            this.Write(" rapplication)\r\n\t\t{\r\n\t\t\tthis.rapplication = rapplication;\r\n\t\t}\r\n\r\n\t");
            
            #line 28 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 foreach(var model in Application.Models) { 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 29 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 var staticInstanceIds = model.StaticInstanceIds; 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 30 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 foreach(var staticInstanceId in staticInstanceIds) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 31 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 if(model.Members.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\r\n\t\tpublic ");
            
            #line 33 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.FullName));
            
            #line default
            #line hidden
            this.Write(" Get");
            
            #line 33 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Name));
            
            #line default
            #line hidden
            
            #line 33 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(staticInstanceIds.Count > 1 ? staticInstanceId.ToUpperInitial() : ""));
            
            #line default
            #line hidden
            this.Write("()\r\n\t\t{\r\n\t\t\treturn new ");
            
            #line 35 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.FullName));
            
            #line default
            #line hidden
            this.Write("(rapplication.Get(\"");
            
            #line 35 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(staticInstanceId));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 35 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\"));\r\n\t\t}\r\n\r\n\t\t\t");
            
            #line 38 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\tpublic ");
            
            #line 40 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.FullName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 40 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Name));
            
            #line default
            #line hidden
            
            #line 40 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(staticInstanceIds.Count > 1 ? staticInstanceId.ToUpperInitial() : ""));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t{\r\n\t\t\tget { return new ");
            
            #line 42 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.FullName));
            
            #line default
            #line hidden
            this.Write("(rapplication.Get(\"");
            
            #line 42 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(staticInstanceId));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 42 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\")); }\r\n\t\t}\r\n\r\n\t\t\t");
            
            #line 45 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 46 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 48 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 if(model.CanInitialize) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 49 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 foreach(var group in model.Initializer.Groups) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tpublic ");
            
            #line 51 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.FullName));
            
            #line default
            #line hidden
            this.Write(" New");
            
            #line 51 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t(");
            
            #line 52 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", group.Select(p => p.Model.FullName + " " + p.Id))));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t{\r\n\t\t\t\treturn new ");
            
            #line 54 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.FullName));
            
            #line default
            #line hidden
            this.Write("(rapplication, ");
            
            #line 54 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", group.Select(p => p.Id))));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t}\r\n\r\n\t\t\t");
            
            #line 57 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 58 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 59 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t}\r\n}\r\n\r\n");
            
            #line 63 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 65 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 foreach(var model in Application.Models) { 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 67 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic class ");
            
            #line 69 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\t");
            
            #line 71 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AccessModifier));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 71 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Robject>()));
            
            #line default
            #line hidden
            this.Write(" Robject { get; private set; }\r\n\t\t");
            
            #line 72 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AccessModifier));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 72 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 72 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Robject>()));
            
            #line default
            #line hidden
            this.Write(" robject)\r\n\t\t{\r\n\t\t\tRobject = robject;\r\n\t\t}\r\n\r\n\t");
            
            #line 77 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 if(model.CanInitialize) { 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 78 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 foreach(var group in model.Initializer.Groups) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 80 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AccessModifier));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 80 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t(");
            
            #line 81 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Rapplication>()));
            
            #line default
            #line hidden
            this.Write(" rapplication, ");
            
            #line 81 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", group.Select(p => p.Model.FullName + " " + p.Id))));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tRobject = rapplication\r\n\t\t\t\t.Init(\"");
            
            #line 84 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\"\r\n\t\t\t");
            
            #line 85 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 foreach(var parameter in group) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t, ");
            
            #line 86 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 ModelToRvariable(parameter, "rapplication"); 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 87 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t);\r\n\t\t}\r\n\r\n\t\t");
            
            #line 91 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 92 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 94 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 foreach(var member in model.Members) { 
            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 95 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnModel.FullName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 95 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Id));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\treturn Robject[\"");
            
            #line 99 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Id));
            
            #line default
            #line hidden
            this.Write("\"].Get().");
            
            #line 99 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 RobjectToModel(member.ReturnModel); 
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n\t\t}\r\n\t");
            
            #line 102 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 104 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 foreach(var operation in model.Operations) { 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 105 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 foreach(var group in operation.Groups) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 107 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ReturnModel.FullName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 107 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Id));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t(");
            
            #line 108 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", group.Select(p => p.Model.FullName + " " + p.Id))));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tvar ");
            
            #line 110 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Id));
            
            #line default
            #line hidden
            this.Write("_result = Robject.Perform\r\n\t\t\t\t(\r\n\t\t\t\t\"");
            
            #line 112 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Id));
            
            #line default
            #line hidden
            this.Write("\"\r\n\t\t\t");
            
            #line 113 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 foreach(var parameter in group) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t, ");
            
            #line 114 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 ModelToRvariable(parameter); 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 115 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t)\r\n\t\t\t;\r\n\t\t\t\r\n\t\t\t");
            
            #line 119 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 if(!operation.ReturnModel.IsVoid) { 
            
            #line default
            #line hidden
            this.Write("\t\t\treturn ");
            
            #line 120 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Id));
            
            #line default
            #line hidden
            this.Write("_result.");
            
            #line 120 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 RobjectToModel(operation.ReturnModel); 
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t");
            
            #line 121 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\t");
            
            #line 124 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 125 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"
		public void Invalidate()
		{
			Robject.Invalidate();
		}
		
		public override string ToString() { return ToString(false); }
		public string ToString(bool includeDebugInfo)
		{
			if(!includeDebugInfo) { return Robject.Value; }
		
			return string.Format(""[Id: {0}, Value: {1}]"", Robject.Id, ToString());
		}

		public override bool Equals(object obj)
		{
			if(obj == null)
				return false;
			if(ReferenceEquals(this, obj))
				return true;
			if(obj.GetType() != typeof(");
            
            #line 146 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.FullName));
            
            #line default
            #line hidden
            this.Write("))\r\n\t\t\t\treturn false;\r\n\r\n\t\t\tvar other = (");
            
            #line 149 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.FullName));
            
            #line default
            #line hidden
            this.Write(")obj;\r\n\t\t\t\r\n\t\t\treturn Robject.Equals(other.Robject);\r\n\t\t}\r\n\t\t\r\n\t\tpublic override " +
                    "int GetHashCode()\r\n\t\t{\r\n\t\t\treturn Robject.GetHashCode();\r\n\t\t}\r\n\t}\r\n}\r\n\r\n");
            
            #line 161 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 163 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 

protected string Type<T>() { return typeof(T).FullName; }
protected string AccessModifier { get { return Application.ApiExists ? "internal" : "public"; } } 

protected void RobjectToModel(ObjectCodeModel model)
{ 
	if(model.IsList) { 
        
        #line default
        #line hidden
        
        #line 170 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\r\n\t\tAsList(robj =>\r\n\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 174 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 if(model.IsValueModel) { 
        
        #line default
        #line hidden
        
        #line 174 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\r\n\t\t\t");

        
        #line default
        #line hidden
        
        #line 176 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(model.GetStringToValueCode("robj")));

        
        #line default
        #line hidden
        
        #line 176 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\r\n\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 178 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } else { 
        
        #line default
        #line hidden
        
        #line 178 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\r\n\t\t\tnew ");

        
        #line default
        #line hidden
        
        #line 180 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(model.FullNameIgnoringList));

        
        #line default
        #line hidden
        
        #line 180 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("(robj)\r\n\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 182 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
        
        #line default
        #line hidden
        
        #line 182 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\r\n\t\t)\r\n\r\n\t");

        
        #line default
        #line hidden
        
        #line 186 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } else { 
        
        #line default
        #line hidden
        
        #line 186 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\r\n\t\tAs(robj =>\r\n\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 190 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 if(model.IsValueModel) { 
        
        #line default
        #line hidden
        
        #line 190 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\r\n\t\t\t");

        
        #line default
        #line hidden
        
        #line 192 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(model.GetStringToValueCode("robj")));

        
        #line default
        #line hidden
        
        #line 192 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\r\n\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 194 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } else { 
        
        #line default
        #line hidden
        
        #line 194 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\r\n\t\t\tnew ");

        
        #line default
        #line hidden
        
        #line 196 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(model.FullNameIgnoringList));

        
        #line default
        #line hidden
        
        #line 196 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("(robj)\r\n\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 198 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
        
        #line default
        #line hidden
        
        #line 198 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\r\n\t\t)\r\n\r\n\t");

        
        #line default
        #line hidden
        
        #line 202 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
        
        #line default
        #line hidden
        
        #line 204 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"


}

protected void ModelToRvariable(ParameterCodeModel parameter) { ModelToRvariable(parameter, "Robject.Application"); }
protected void ModelToRvariable(ParameterCodeModel parameter, string rapplicationVar)
{ 
	var model = parameter.Model; 
	
	if(model.IsList) { 
        
        #line default
        #line hidden
        
        #line 213 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\t\t");

        
        #line default
        #line hidden
        
        #line 214 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 if(model.IsValueModel) { 
        
        #line default
        #line hidden
        
        #line 214 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\r\n\t\t\t");

        
        #line default
        #line hidden
        
        #line 216 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(rapplicationVar));

        
        #line default
        #line hidden
        
        #line 216 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(".NewVarList(\"");

        
        #line default
        #line hidden
        
        #line 216 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Id));

        
        #line default
        #line hidden
        
        #line 216 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\", ");

        
        #line default
        #line hidden
        
        #line 216 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Id));

        
        #line default
        #line hidden
        
        #line 216 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(", o => ");

        
        #line default
        #line hidden
        
        #line 216 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(model.GetValueToStringCode("o")));

        
        #line default
        #line hidden
        
        #line 216 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(", \"");

        
        #line default
        #line hidden
        
        #line 216 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));

        
        #line default
        #line hidden
        
        #line 216 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\")\r\n\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 218 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } else { 
        
        #line default
        #line hidden
        
        #line 218 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\r\n\t\t\t");

        
        #line default
        #line hidden
        
        #line 220 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(rapplicationVar));

        
        #line default
        #line hidden
        
        #line 220 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(".NewVarList(\"");

        
        #line default
        #line hidden
        
        #line 220 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Id));

        
        #line default
        #line hidden
        
        #line 220 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\", ");

        
        #line default
        #line hidden
        
        #line 220 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Id));

        
        #line default
        #line hidden
        
        #line 220 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(".Select(o => o.Robject))\r\n\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 222 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
        
        #line default
        #line hidden
        
        #line 222 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\t");

        
        #line default
        #line hidden
        
        #line 223 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } else { 
        
        #line default
        #line hidden
        
        #line 223 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\t\t");

        
        #line default
        #line hidden
        
        #line 224 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 if(model.IsValueModel) { 
        
        #line default
        #line hidden
        
        #line 224 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\r\n\t\t\t");

        
        #line default
        #line hidden
        
        #line 226 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(rapplicationVar));

        
        #line default
        #line hidden
        
        #line 226 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(".NewVar(\"");

        
        #line default
        #line hidden
        
        #line 226 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Id));

        
        #line default
        #line hidden
        
        #line 226 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\", ");

        
        #line default
        #line hidden
        
        #line 226 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Id));

        
        #line default
        #line hidden
        
        #line 226 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(", o => ");

        
        #line default
        #line hidden
        
        #line 226 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(model.GetValueToStringCode("o")));

        
        #line default
        #line hidden
        
        #line 226 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(", \"");

        
        #line default
        #line hidden
        
        #line 226 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));

        
        #line default
        #line hidden
        
        #line 226 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\")\r\n\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 228 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } else { 
        
        #line default
        #line hidden
        
        #line 228 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\r\n\t\t\t");

        
        #line default
        #line hidden
        
        #line 230 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(rapplicationVar));

        
        #line default
        #line hidden
        
        #line 230 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(".NewVar(\"");

        
        #line default
        #line hidden
        
        #line 230 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Id));

        
        #line default
        #line hidden
        
        #line 230 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\", ");

        
        #line default
        #line hidden
        
        #line 230 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Id));

        
        #line default
        #line hidden
        
        #line 230 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write(".Robject)\r\n\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 232 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
        
        #line default
        #line hidden
        
        #line 232 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
this.Write("\t");

        
        #line default
        #line hidden
        
        #line 233 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"
 } 
        
        #line default
        #line hidden
        
        #line 234 "E:\Projects\routine\Routine\Api\Template\T4\ClientApi.tt"


}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class ClientApiBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
