// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Routine.Api.Template
{
    using System;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;
    using Routine.Client;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class ClientApiTemplate : ClientApiTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            
            #line 9 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var model in OperationalModels) { 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 11 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetNamespace(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic interface ");
            
            #line 13 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t");
            
            #line 15 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var member in model.Members) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 17 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnModel.GetFullName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 17 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.GetName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n\t");
            
            #line 18 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 20 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var operation in model.Operations) { 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 21 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var group in operation.Groups) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 23 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ReturnModel.GetFullName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 23 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.GetName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 23 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", group.Select(p => p.ParameterModel.GetFullName() + " " + p.GetName(Mode.Interface)))));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t");
            
            #line 24 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 25 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 27 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var viewModel in model.ViewModels) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 29 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewModel.GetFullName()));
            
            #line default
            #line hidden
            this.Write(" As");
            
            #line 29 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewModel.GetName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write("();\r\n\t");
            
            #line 30 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tvoid Invalidate();\r\n\t\t");
            
            #line 33 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Application.DefaultNamespace));
            
            #line default
            #line hidden
            this.Write(".ObjectIdentifier GetIdentifier();\r\n\t}\r\n}\r\n\r\nnamespace ");
            
            #line 37 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetNamespace(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tinternal class ");
            
            #line 39 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 39 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tinternal ");
            
            #line 41 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Robject>()));
            
            #line default
            #line hidden
            this.Write(" Robject { get; private set; }\r\n\t\tinternal ");
            
            #line 42 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 42 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Robject>()));
            
            #line default
            #line hidden
            this.Write(" robject)\r\n\t\t{\r\n\t\t\tRobject = robject;\r\n\t\t}\r\n\r\n\t");
            
            #line 47 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var member in model.Members) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 49 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnModel.GetFullName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 49 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 49 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.GetName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\tvar __result = Robject[\"");
            
            #line 53 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Id));
            
            #line default
            #line hidden
            this.Write("\"].Get();\r\n\t\t\t\t\r\n\t\t\t\treturn ");
            
            #line 55 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnModel.RenderRvariableToObject("__result", "Robject.Application")));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n\t\t}\r\n\t");
            
            #line 58 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 60 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var operation in model.Operations) { 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 61 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var group in operation.Groups) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 63 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ReturnModel.GetFullName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 63 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 63 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.GetName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t(");
            
            #line 64 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", group.Select(p => p.ParameterModel.GetFullName() + " " + p.GetName(Mode.Interface)))));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tvar __result = Robject.Perform\r\n\t\t\t\t(\r\n\t\t\t\t\"");
            
            #line 68 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Id));
            
            #line default
            #line hidden
            this.Write("\"\r\n\t\t\t");
            
            #line 69 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var parameter in group) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t, ");
            
            #line 70 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.ParameterModel.RenderObjectToRvariable(parameter.Id, parameter.GetName(Mode.Interface), "Robject.Application")));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 71 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t)\r\n\t\t\t;\r\n\t\t\t");
            
            #line 75 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 if(!operation.ReturnModel.IsVoid) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\treturn ");
            
            #line 77 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ReturnModel.RenderRvariableToObject("__result", "Robject.Application")));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t");
            
            #line 78 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t}\r\n\t\t");
            
            #line 81 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 82 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 84 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var viewModel in model.ViewModels) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 86 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewModel.GetFullName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 86 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write(".As");
            
            #line 86 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewModel.GetName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write("() \r\n\t\t{\r\n\t\t\tvar __result = Robject.As(Robject.Application[\"");
            
            #line 88 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewModel.Id));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\r\n\t\t\treturn ");
            
            #line 90 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewModel.RenderRobjectToObject("__result", "Robject.Application")));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t}\r\n\t");
            
            #line 92 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tvoid ");
            
            #line 94 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write(".Invalidate()\r\n\t\t{\r\n\t\t\tRobject.Invalidate();\r\n\t\t}\r\n\r\n\t\t");
            
            #line 99 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Application.DefaultNamespace));
            
            #line default
            #line hidden
            this.Write(".ObjectIdentifier ");
            
            #line 99 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write(".GetIdentifier()\r\n\t\t{\r\n\t\t\treturn new ");
            
            #line 101 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Application.DefaultNamespace));
            
            #line default
            #line hidden
            this.Write(@".ObjectIdentifier(Robject.Id);
		}
		
		public override string ToString()
		{
			return Robject.Value;
		}

		public override bool Equals(object obj)
		{
			if(obj == null)
				return false;
			if(ReferenceEquals(this, obj))
				return true;
			if(obj.GetType() != typeof(");
            
            #line 115 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write("))\r\n\t\t\t\treturn false;\r\n\r\n\t\t\tvar other = (");
            
            #line 118 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write(")obj;\r\n\t\t\t\r\n\t\t\treturn Robject.Equals(other.Robject);\r\n\t\t}\r\n\t\t\r\n\t\tpublic override " +
                    "int GetHashCode()\r\n\t\t{\r\n\t\t\treturn Robject.GetHashCode();\r\n\t\t}\r\n\t}\r\n}\r\n\r\n");
            
            #line 130 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 132 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var model in InitializableOperationalModels) { 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 134 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetNamespace(Mode.FactoryInterface)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic interface ");
            
            #line 136 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.FactoryInterface)));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\t");
            
            #line 138 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var group in model.Initializer.Groups) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 140 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write(" New\r\n\t\t\t(");
            
            #line 141 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", group.Select(p => p.ParameterModel.GetFullName() + " " + p.GetName(Mode.FactoryInterface)))));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t");
            
            #line 142 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n}\r\n\r\nnamespace ");
            
            #line 147 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetNamespace(Mode.Factory)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tinternal class ");
            
            #line 149 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.Factory)));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 149 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.FactoryInterface)));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tinternal ");
            
            #line 151 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Rapplication>()));
            
            #line default
            #line hidden
            this.Write(" Rapplication { get; private set; }\r\n\r\n\t\tpublic ");
            
            #line 153 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.Factory)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 153 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Rapplication>()));
            
            #line default
            #line hidden
            this.Write(" rapplication)\r\n\t\t{\r\n\t\t\tRapplication = rapplication;\r\n\t\t}\r\n\t\t\r\n\t\t");
            
            #line 158 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var group in model.Initializer.Groups) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 160 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 160 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.FactoryInterface)));
            
            #line default
            #line hidden
            this.Write(".New\r\n\t\t\t(");
            
            #line 161 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", group.Select(p => p.ParameterModel.GetFullName() + " " + p.GetName(Mode.FactoryInterface)))));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tvar robject = Rapplication\r\n\t\t\t\t.Init(\"");
            
            #line 164 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\"\r\n\t\t\t");
            
            #line 165 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var parameter in group) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t, ");
            
            #line 167 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.ParameterModel.RenderObjectToRvariable(parameter.Id, parameter.GetName(Mode.FactoryInterface), "Rapplication")));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 168 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t);\r\n\r\n\t\t\treturn new ");
            
            #line 172 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write("(robject);\r\n\t\t}\r\n\t\t");
            
            #line 174 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n}\r\n");
            
            #line 178 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 180 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var model in InitializeOnlyStructModels) { 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 182 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetNamespace(Mode.InitializeOnlyStruct)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic struct ");
            
            #line 184 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.InitializeOnlyStruct)));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tprivate readonly int group;\r\n\t\t");
            
            #line 187 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var parameter in model.Initializer.Parameters) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 189 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.ParameterModel.GetFullName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 189 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.GetName(Mode.InitializeOnlyStructProperty)));
            
            #line default
            #line hidden
            this.Write(" { get; private set; }\r\n\t\t");
            
            #line 190 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 192 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 var groups = model.Initializer.Groups; 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 193 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 for(int i = 0; i < groups.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 194 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 var group = groups[i]; 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 196 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.InitializeOnlyStruct)));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t(");
            
            #line 197 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", group.Select(p => p.ParameterModel.GetFullName() + " " + p.GetName(Mode.InitializeOnlyStruct)))));
            
            #line default
            #line hidden
            this.Write(") : this()\r\n\t\t{\r\n\t\t\tthis.group = ");
            
            #line 199 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t");
            
            #line 200 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var parameter in group) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\t");
            
            #line 202 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.GetName(Mode.InitializeOnlyStructProperty)));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 202 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.GetName(Mode.InitializeOnlyStruct)));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t");
            
            #line 203 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t}\r\n\t\t");
            
            #line 206 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tinternal ");
            
            #line 208 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Robject>()));
            
            #line default
            #line hidden
            this.Write(" ToRobject(");
            
            #line 208 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Rtype>()));
            
            #line default
            #line hidden
            this.Write(" rtype)\r\n\t\t{\r\n\t\t\tvar initParams = new ");
            
            #line 210 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<List<Rvariable>>()));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\t\t\r\n\t\t\t");
            
            #line 212 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 for(int i = 0; i < groups.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 213 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 var group = groups[i]; 
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\t");
            
            #line 215 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i > 0 ? "else " : string.Empty));
            
            #line default
            #line hidden
            this.Write("if(group == ");
            
            #line 215 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t{\r\n\t\t\t\t");
            
            #line 217 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var parameter in group) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\t\tinitParams.Add(");
            
            #line 219 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.ParameterModel.RenderObjectToRvariable(parameter.Id, parameter.GetName(Mode.InitializeOnlyStructProperty), "rtype.Application")));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t");
            
            #line 220 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t}\r\n\t\t\t");
            
            #line 223 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\treturn rtype.Init(initParams);\r\n\t\t}\r\n\t}\r\n}\r\n\r\n");
            
            #line 230 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 232 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var model in EnumModels) { 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 234 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetNamespace(Mode.Enum)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic enum ");
            
            #line 236 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.Enum)));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t");
            
            #line 238 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var staticInstance in model.Type.StaticInstances) { 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t\t");
            
            #line 240 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(staticInstance.GetEnumMemberName()));
            
            #line default
            #line hidden
            this.Write(",\r\n\t");
            
            #line 241 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n}\r\n\r\nnamespace ");
            
            #line 246 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetNamespace(Mode.EnumConverter)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tinternal static class ");
            
            #line 248 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.EnumConverter)));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tprivate static readonly ");
            
            #line 250 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Dictionary<object, string>>()));
            
            #line default
            #line hidden
            this.Write(" ids = new ");
            
            #line 250 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Dictionary<object, string>>()));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\tprivate static readonly ");
            
            #line 251 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Dictionary<string, object>>()));
            
            #line default
            #line hidden
            this.Write(" values = new ");
            
            #line 251 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Dictionary<string, object>>()));
            
            #line default
            #line hidden
            this.Write("();\r\n\r\n\t\tstatic ");
            
            #line 253 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.EnumConverter)));
            
            #line default
            #line hidden
            this.Write("()\r\n\t\t{\r\n\t");
            
            #line 255 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var staticInstance in model.Type.StaticInstances) { 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t\t\tids.Add(");
            
            #line 257 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Enum) + "." + staticInstance.GetEnumMemberName()));
            
            #line default
            #line hidden
            this.Write(", \"");
            
            #line 257 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(staticInstance.Id));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t");
            
            #line 258 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 260 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var staticInstance in model.Type.StaticInstances) { 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t\t\tvalues.Add(\"");
            
            #line 262 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(staticInstance.Id));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 262 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Enum) + "." + staticInstance.GetEnumMemberName()));
            
            #line default
            #line hidden
            this.Write(");\r\n\t");
            
            #line 263 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t}\r\n\r\n\t\tinternal static ");
            
            #line 267 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Robject>()));
            
            #line default
            #line hidden
            this.Write(" ToRobject(");
            
            #line 267 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Enum)));
            
            #line default
            #line hidden
            this.Write(" value, ");
            
            #line 267 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Rtype>()));
            
            #line default
            #line hidden
            this.Write(" rtype)\r\n\t\t{\r\n\t\t\treturn rtype.Get(ids[value]);\r\n\t\t}\r\n\r\n\t\tinternal static ");
            
            #line 272 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Enum)));
            
            #line default
            #line hidden
            this.Write(" ToEnum(");
            
            #line 272 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Robject>()));
            
            #line default
            #line hidden
            this.Write(" robject)\r\n\t\t{\r\n\t\t\treturn (");
            
            #line 274 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Enum)));
            
            #line default
            #line hidden
            this.Write(")values[robject.Id];\r\n\t\t}\r\n\t}\r\n}\r\n\r\n");
            
            #line 279 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 281 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Application.DefaultNamespace));
            
            #line default
            #line hidden
            this.Write(@"
{
	public class ObjectIdentifier : System.IEquatable<ObjectIdentifier>
	{
		public string Value { get; private set; }

		internal ObjectIdentifier(string value)
		{
			Value = value;
		}

		public override string ToString()
		{
			return Value;
		}

		public override bool Equals(object obj)
		{
			if (ReferenceEquals(null, obj)) return false;
			if (ReferenceEquals(this, obj)) return true;
			if (obj.GetType() != GetType()) return false;
			return Equals((ObjectIdentifier)obj);
		}

		public bool Equals(ObjectIdentifier other)
		{
			return Equals(Value, other.Value);
		}

		public override int GetHashCode()
		{
			return (Value != null ? Value.GetHashCode() : 0);
		}
	}

	public interface I");
            
            #line 316 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tT Get<T>(string instanceId);\r\n\t\tobject Get(");
            
            #line 319 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Type>()));
            
            #line default
            #line hidden
            this.Write(" type, string instanceId);\r\n\r\n\t\tT Get<T>();\r\n\t\tobject Get(");
            
            #line 322 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Type>()));
            
            #line default
            #line hidden
            this.Write(" type);\r\n\t}\r\n\r\n\tpublic class ");
            
            #line 325 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write(" : I");
            
            #line 325 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tprivate readonly ");
            
            #line 327 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Rapplication>()));
            
            #line default
            #line hidden
            this.Write(" rapplication;\r\n\r\n\t\tpublic ");
            
            #line 329 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 329 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Rapplication>()));
            
            #line default
            #line hidden
            this.Write(" rapplication)\r\n\t\t{\r\n\t\t\tthis.rapplication = rapplication;\r\n\t\t}\r\n\r\n\r\n\t\tT I");
            
            #line 335 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write(".Get<T>(string instanceId) { return (T)((I");
            
            #line 335 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write(")this).Get(typeof(T), instanceId); }\r\n\t\tobject I");
            
            #line 336 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write(".Get(");
            
            #line 336 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Type>()));
            
            #line default
            #line hidden
            this.Write(" type, string instanceId)\r\n\t\t{\r\n\t");
            
            #line 338 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var model in GetInstanceModels) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\tif(type.IsAssignableFrom(typeof(");
            
            #line 340 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write(")))\r\n\t\t\t{\r\n\t\t\t\treturn new ");
            
            #line 342 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write("(rapplication.Get(instanceId, \"");
            
            #line 342 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\"));\r\n\t\t\t}\r\n\t");
            
            #line 344 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t\t\tthrow new GetInstanceException(type);\r\n\t\t}\r\n\r\n\t\tT I");
            
            #line 349 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write(".Get<T>() { return (T)((I");
            
            #line 349 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write(")this).Get(typeof(T)); }\r\n\t\tobject I");
            
            #line 350 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write(".Get(");
            
            #line 350 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Type>()));
            
            #line default
            #line hidden
            this.Write(" type)\r\n\t\t{\r\n\t");
            
            #line 352 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var model in SingletonModels) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tif(type.IsAssignableFrom(typeof(");
            
            #line 354 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write(")))\r\n\t\t\t{\r\n\t\t\t\treturn new ");
            
            #line 356 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write("(rapplication.Get(\"");
            
            #line 356 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Type.StaticInstances[0].Id));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 356 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Type.StaticInstances[0].ActualType.Id));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 356 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Type.StaticInstances[0].ViewType.Id));
            
            #line default
            #line hidden
            this.Write("\"));\r\n\t\t\t}\r\n\t");
            
            #line 358 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t");
            
            #line 360 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var model in InitializableOperationalModels) { 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t\t\tif(type.IsAssignableFrom(typeof(");
            
            #line 362 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Factory)));
            
            #line default
            #line hidden
            this.Write(")))\r\n\t\t\t{\r\n\t\t\t\treturn new ");
            
            #line 364 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Factory)));
            
            #line default
            #line hidden
            this.Write("(rapplication);\r\n\t\t\t}\r\n\t");
            
            #line 366 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tthrow new SingletonException(type);\r\n\t\t}\r\n\t}\r\n\t\r\n\tpublic class GetInstanceEx" +
                    "ception : ");
            
            #line 372 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Exception>()));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tpublic GetInstanceException(");
            
            #line 374 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Type>()));
            
            #line default
            #line hidden
            this.Write(" targetType) : base(string.Format(\"Cannot get instance for {0}. Given type should" +
                    " be non view type and rendered as interface.\", targetType)) { }\r\n\t}\r\n\r\n\tpublic c" +
                    "lass SingletonException : ");
            
            #line 377 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Exception>()));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tpublic SingletonException(");
            
            #line 379 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Type>()));
            
            #line default
            #line hidden
            this.Write(" targetType) : base(string.Format(\"Given type {0} is not singleton\", targetType))" +
                    " { }\r\n\t}\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 383 "D:\Projects\routine\routine\Routine\Api\Template\ClientApiTemplate.tt"
 

protected string Type<T>() { return typeof(T).ToCSharpString(); }


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class ClientApiTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
