// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Routine.Api.Template
{
    using System;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;
    using Routine.Client;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class ClientApiTemplate : ClientApiTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            
            #line 9 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var model in OperationalModels) { 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 11 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetNamespace(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic interface ");
            
            #line 13 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t");
            
            #line 15 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var member in model.Members) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 17 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnModel.GetFullName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 17 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.GetName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n\t");
            
            #line 18 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 20 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var operation in model.Operations) { 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 21 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var group in operation.Groups) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 23 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ReturnModel.GetFullName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 23 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.GetName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 23 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", group.Select(p => p.ParameterModel.GetFullName() + " " + p.GetName(Mode.Interface)))));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t");
            
            #line 24 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 25 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tvoid Invalidate();\r\n\t}\r\n}\r\n\r\nnamespace ");
            
            #line 31 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetNamespace(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tinternal class ");
            
            #line 33 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 33 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tinternal ");
            
            #line 35 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Robject>()));
            
            #line default
            #line hidden
            this.Write(" Robject { get; private set; }\r\n\t\tinternal ");
            
            #line 36 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 36 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Robject>()));
            
            #line default
            #line hidden
            this.Write(" robject)\r\n\t\t{\r\n\t\t\tRobject = robject;\r\n\t\t}\r\n\r\n\t");
            
            #line 41 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var member in model.Members) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 43 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnModel.GetFullName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 43 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 43 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.GetName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\tvar result = Robject[\"");
            
            #line 47 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Id));
            
            #line default
            #line hidden
            this.Write("\"].Get();\r\n\t\t\t\t\r\n\t\t\t\treturn ");
            
            #line 49 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnModel.RenderRvariableToObject("result", "Robject.Application")));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n\t\t}\r\n\t");
            
            #line 52 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 54 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var operation in model.Operations) { 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 55 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var group in operation.Groups) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 57 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ReturnModel.GetFullName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 57 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 57 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.GetName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t(");
            
            #line 58 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", group.Select(p => p.ParameterModel.GetFullName() + " " + p.GetName(Mode.Interface)))));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tvar __result = Robject.Perform\r\n\t\t\t\t(\r\n\t\t\t\t\"");
            
            #line 62 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Id));
            
            #line default
            #line hidden
            this.Write("\"\r\n\t\t\t");
            
            #line 63 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var parameter in group) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t, ");
            
            #line 64 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.ParameterModel.RenderObjectToRvariable(parameter.Id, parameter.GetName(Mode.Interface), "Robject.Application")));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 65 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t)\r\n\t\t\t;\r\n\t\t\t");
            
            #line 69 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 if(!operation.ReturnModel.IsVoid) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\treturn ");
            
            #line 71 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ReturnModel.RenderRvariableToObject("__result", "Robject.Application")));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t");
            
            #line 72 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t}\r\n\t\t");
            
            #line 75 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 76 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tvoid ");
            
            #line 78 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write(@".Invalidate()
		{
			Robject.Invalidate();
		}
		
		public override string ToString()
		{
			return string.Format(""{0} ({1})"", Robject.Value, Robject.Id);
		}

		public override bool Equals(object obj)
		{
			if(obj == null)
				return false;
			if(ReferenceEquals(this, obj))
				return true;
			if(obj.GetType() != typeof(");
            
            #line 94 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write("))\r\n\t\t\t\treturn false;\r\n\r\n\t\t\tvar other = (");
            
            #line 97 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write(")obj;\r\n\t\t\t\r\n\t\t\treturn Robject.Equals(other.Robject);\r\n\t\t}\r\n\t\t\r\n\t\tpublic override " +
                    "int GetHashCode()\r\n\t\t{\r\n\t\t\treturn Robject.GetHashCode();\r\n\t\t}\r\n\t}\r\n}\r\n\r\n");
            
            #line 109 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 111 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var model in InitializableOperationalModels) { 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 113 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetNamespace(Mode.FactoryInterface)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic interface ");
            
            #line 115 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.FactoryInterface)));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\t");
            
            #line 117 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var group in model.Initializer.Groups) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 119 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write(" New\r\n\t\t\t(");
            
            #line 120 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", group.Select(p => p.ParameterModel.GetFullName() + " " + p.GetName(Mode.FactoryInterface)))));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t");
            
            #line 121 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n}\r\n\r\nnamespace ");
            
            #line 126 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetNamespace(Mode.Factory)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tinternal class ");
            
            #line 128 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.Factory)));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 128 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.FactoryInterface)));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tinternal ");
            
            #line 130 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Rapplication>()));
            
            #line default
            #line hidden
            this.Write(" Rapplication { get; private set; }\r\n\r\n\t\tpublic ");
            
            #line 132 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.Factory)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 132 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Rapplication>()));
            
            #line default
            #line hidden
            this.Write(" rapplication)\r\n\t\t{\r\n\t\t\tRapplication = rapplication;\r\n\t\t}\r\n\t\t\r\n\t\t");
            
            #line 137 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var group in model.Initializer.Groups) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 139 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Interface)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 139 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.FactoryInterface)));
            
            #line default
            #line hidden
            this.Write(".New\r\n\t\t\t(");
            
            #line 140 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", group.Select(p => p.ParameterModel.GetFullName() + " " + p.GetName(Mode.FactoryInterface)))));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tvar robject = Rapplication\r\n\t\t\t\t.Init(\"");
            
            #line 143 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\"\r\n\t\t\t");
            
            #line 144 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var parameter in group) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t, ");
            
            #line 146 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.ParameterModel.RenderObjectToRvariable(parameter.Id, parameter.GetName(Mode.FactoryInterface), "Rapplication")));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 147 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t);\r\n\r\n\t\t\treturn new ");
            
            #line 151 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write("(robject);\r\n\t\t}\r\n\t\t");
            
            #line 153 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n}\r\n");
            
            #line 157 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 159 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var model in InitializeOnlyStructModels) { 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 161 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetNamespace(Mode.InitializeOnlyStruct)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic struct ");
            
            #line 163 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.InitializeOnlyStruct)));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tprivate readonly int group;\r\n\t\t");
            
            #line 166 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var parameter in model.Initializer.Parameters) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 168 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.ParameterModel.GetFullName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 168 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.GetName(Mode.InitializeOnlyStructProperty)));
            
            #line default
            #line hidden
            this.Write(" { get; private set; }\r\n\t\t");
            
            #line 169 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 171 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 var groups = model.Initializer.Groups; 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 172 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 for(int i = 0; i < groups.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 173 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 var group = groups[i]; 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 175 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.InitializeOnlyStruct)));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t(");
            
            #line 176 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", group.Select(p => p.ParameterModel.GetFullName() + " " + p.GetName(Mode.InitializeOnlyStruct)))));
            
            #line default
            #line hidden
            this.Write(") : this()\r\n\t\t{\r\n\t\t\tthis.group = ");
            
            #line 178 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t");
            
            #line 179 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var parameter in group) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\t");
            
            #line 181 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.GetName(Mode.InitializeOnlyStructProperty)));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 181 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.GetName(Mode.InitializeOnlyStruct)));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t");
            
            #line 182 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t}\r\n\t\t");
            
            #line 185 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tinternal ");
            
            #line 187 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Robject>()));
            
            #line default
            #line hidden
            this.Write(" ToRobject(");
            
            #line 187 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Rtype>()));
            
            #line default
            #line hidden
            this.Write(" rtype)\r\n\t\t{\r\n\t\t\tvar initParams = new ");
            
            #line 189 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<List<Rvariable>>()));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\t\t\r\n\t\t\t");
            
            #line 191 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 for(int i = 0; i < groups.Count; i++) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 192 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 var group = groups[i]; 
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\t");
            
            #line 194 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i > 0 ? "else " : string.Empty));
            
            #line default
            #line hidden
            this.Write("if(group == ");
            
            #line 194 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t{\r\n\t\t\t\t");
            
            #line 196 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var parameter in group) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\t\tinitParams.Add(");
            
            #line 198 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.ParameterModel.RenderObjectToRvariable(parameter.Id, parameter.GetName(Mode.InitializeOnlyStructProperty), "rtype.Application")));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t");
            
            #line 199 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t}\r\n\t\t\t");
            
            #line 202 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\treturn rtype.Init(initParams);\r\n\t\t}\r\n\t}\r\n}\r\n\r\n");
            
            #line 209 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 211 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var model in EnumModels) { 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 213 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetNamespace(Mode.Enum)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic enum ");
            
            #line 215 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.Enum)));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t");
            
            #line 217 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var staticInstance in model.Type.StaticInstances) { 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t\t");
            
            #line 219 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(staticInstance.GetEnumMemberName()));
            
            #line default
            #line hidden
            this.Write(",\r\n\t");
            
            #line 220 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n}\r\n\r\nnamespace ");
            
            #line 225 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetNamespace(Mode.EnumConverter)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tinternal static class ");
            
            #line 227 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.EnumConverter)));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tprivate static readonly ");
            
            #line 229 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Dictionary<object, string>>()));
            
            #line default
            #line hidden
            this.Write(" ids = new ");
            
            #line 229 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Dictionary<object, string>>()));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\tprivate static readonly ");
            
            #line 230 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Dictionary<string, object>>()));
            
            #line default
            #line hidden
            this.Write(" values = new ");
            
            #line 230 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Dictionary<string, object>>()));
            
            #line default
            #line hidden
            this.Write("();\r\n\r\n\t\tstatic ");
            
            #line 232 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetName(Mode.EnumConverter)));
            
            #line default
            #line hidden
            this.Write("()\r\n\t\t{\r\n\t");
            
            #line 234 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var staticInstance in model.Type.StaticInstances) { 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t\t\tids.Add(");
            
            #line 236 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Enum) + "." + staticInstance.GetEnumMemberName()));
            
            #line default
            #line hidden
            this.Write(", \"");
            
            #line 236 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(staticInstance.Id));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t");
            
            #line 237 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 239 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var staticInstance in model.Type.StaticInstances) { 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t\t\tvalues.Add(\"");
            
            #line 241 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(staticInstance.Id));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 241 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Enum) + "." + staticInstance.GetEnumMemberName()));
            
            #line default
            #line hidden
            this.Write(");\r\n\t");
            
            #line 242 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t}\r\n\r\n\t\tinternal static ");
            
            #line 246 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Robject>()));
            
            #line default
            #line hidden
            this.Write(" ToRobject(");
            
            #line 246 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Enum)));
            
            #line default
            #line hidden
            this.Write(" value, ");
            
            #line 246 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Rtype>()));
            
            #line default
            #line hidden
            this.Write(" rtype)\r\n\t\t{\r\n\t\t\treturn rtype.Get(ids[value]);\r\n\t\t}\r\n\r\n\t\tinternal static ");
            
            #line 251 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Enum)));
            
            #line default
            #line hidden
            this.Write(" ToEnum(");
            
            #line 251 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Robject>()));
            
            #line default
            #line hidden
            this.Write(" robject)\r\n\t\t{\r\n\t\t\treturn (");
            
            #line 253 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Enum)));
            
            #line default
            #line hidden
            this.Write(")values[robject.Id];\r\n\t\t}\r\n\t}\r\n}\r\n\r\n");
            
            #line 258 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 260 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Application.DefaultNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic interface I");
            
            #line 262 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tT Get<T>(string instanceId);\r\n\t\tobject Get(");
            
            #line 265 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Type>()));
            
            #line default
            #line hidden
            this.Write(" type, string instanceId);\r\n\r\n\t\tT Get<T>();\r\n\t\tobject Get(");
            
            #line 268 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Type>()));
            
            #line default
            #line hidden
            this.Write(" type);\r\n\t}\r\n\r\n\tpublic class ");
            
            #line 271 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write(" : I");
            
            #line 271 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tprivate readonly ");
            
            #line 273 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Rapplication>()));
            
            #line default
            #line hidden
            this.Write(" rapplication;\r\n\r\n\t\tpublic ");
            
            #line 275 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 275 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Rapplication>()));
            
            #line default
            #line hidden
            this.Write(" rapplication)\r\n\t\t{\r\n\t\t\tthis.rapplication = rapplication;\r\n\t\t}\r\n\r\n\r\n\t\tT I");
            
            #line 281 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write(".Get<T>(string instanceId) { return (T)((I");
            
            #line 281 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write(")this).Get(typeof(T), instanceId); }\r\n\t\tobject I");
            
            #line 282 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write(".Get(");
            
            #line 282 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Type>()));
            
            #line default
            #line hidden
            this.Write(" type, string instanceId)\r\n\t\t{\r\n\t");
            
            #line 284 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var model in GetInstanceModels) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\tif(type.IsAssignableFrom(typeof(");
            
            #line 286 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write(")))\r\n\t\t\t{\r\n\t\t\t\treturn new ");
            
            #line 288 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write("(rapplication.Get(instanceId, \"");
            
            #line 288 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\"));\r\n\t\t\t}\r\n\t");
            
            #line 290 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t\t\tthrow new GetInstanceException(type);\r\n\t\t}\r\n\r\n\t\tT I");
            
            #line 295 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write(".Get<T>() { return (T)((I");
            
            #line 295 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write(")this).Get(typeof(T)); }\r\n\t\tobject I");
            
            #line 296 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiName));
            
            #line default
            #line hidden
            this.Write(".Get(");
            
            #line 296 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Type>()));
            
            #line default
            #line hidden
            this.Write(" type)\r\n\t\t{\r\n\t");
            
            #line 298 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var model in SingletonModels) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tif(type.IsAssignableFrom(typeof(");
            
            #line 300 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write(")))\r\n\t\t\t{\r\n\t\t\t\treturn new ");
            
            #line 302 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Concrete)));
            
            #line default
            #line hidden
            this.Write("(rapplication.Get(\"");
            
            #line 302 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Type.StaticInstances[0].Id));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 302 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Type.StaticInstances[0].ActualType.Id));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 302 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Type.StaticInstances[0].ViewType.Id));
            
            #line default
            #line hidden
            this.Write("\"));\r\n\t\t\t}\r\n\t");
            
            #line 304 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t");
            
            #line 306 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 foreach(var model in InitializableOperationalModels) { 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t\t\tif(type.IsAssignableFrom(typeof(");
            
            #line 308 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Factory)));
            
            #line default
            #line hidden
            this.Write(")))\r\n\t\t\t{\r\n\t\t\t\treturn new ");
            
            #line 310 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.GetFullName(Mode.Factory)));
            
            #line default
            #line hidden
            this.Write("(rapplication);\r\n\t\t\t}\r\n\t");
            
            #line 312 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tthrow new SingletonException(type);\r\n\t\t}\r\n\t}\r\n\t\r\n\tpublic class GetInstanceEx" +
                    "ception : ");
            
            #line 318 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Exception>()));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tpublic GetInstanceException(");
            
            #line 320 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Type>()));
            
            #line default
            #line hidden
            this.Write(" targetType) : base(string.Format(\"Cannot get instance for {0}. Given type should" +
                    " be non view type and rendered as interface.\", targetType)) { }\r\n\t}\r\n\r\n\tpublic c" +
                    "lass SingletonException : ");
            
            #line 323 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Exception>()));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tpublic SingletonException(");
            
            #line 325 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type<Type>()));
            
            #line default
            #line hidden
            this.Write(" targetType) : base(string.Format(\"Given type {0} is not singleton\", targetType))" +
                    " { }\r\n\t}\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 329 "E:\Projects\routine\Routine\Api\Template\ClientApiTemplate.tt"
 

protected string Type<T>() { return typeof(T).ToCSharpString(); }


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class ClientApiTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
