-
  image: Visual Studio 2017

# configuration for "master" branch
# build in Release mode and deploy to Nuget
-
  branches:
    only:
      - master
  configuration: Release
  nuget:
    disable_publish_on_pr: true
  install:
    - ps: .\Tools\Appveyor\install_dotnet_devpack.ps1
  before_build:
    - dotnet restore .\Routine.sln
  build_script:
    - dotnet build .\Routine.sln
  after_test:
    - ps: .\Routine\Scripts\BuildNugetPackage.ps1

  deploy:
    # The following is the details allowing for appveyor to push the 
    # new version of the package to nuget.org.
  - provider: NuGet
    name: production
    api_key: 
      secure: 0uEiB3xE0Pxwlk20sxtf+Vy9WZQrbA2XYIbZbvQZficGLgJ7u8Cvcfu/t2T/rlmq
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
  artifacts:
  - path: .\artifacts\**\*.nupkg
    name: Nuget
# configuration for "develop" branch
# build in Release mode and create Nuget pack
-
  branches:
    only:
      - develop
  configuration: Release
  nuget:
    disable_publish_on_pr: true
  install:
    - ps: .\Tools\Appveyor\install_dotnet_devpack.ps1
  before_build:
    - dotnet restore .\Routine.sln
  build_script:
    - dotnet build .\Routine.sln

# configuration for all other branches except "master" and "develop"
# build in Debug mode and deploy locally for testing
-
  branches:
    except:
      - master
      - develop
  configuration: Release
  install:
    - ps: .\Tools\Appveyor\install_dotnet_devpack.ps1
  before_build:
    - dotnet restore .\Routine.sln
  build_script:
    - dotnet build .\Routine.sln
  test:
    assemblies:
      only:
        - .\Routine\Routine.Test\bin\Release\$(configuration)\Routine.Test.dll
        - .\Routine\Routine.Test.Performance\bin\Release\net48\Routine.Test.Performance.dll
  after_test:
    - ps: .\Routine\Scripts\BuildNugetPackage.ps1