# configuration for "master" branch
# build in Release mode and deploy to Nuget
-
  branches:
    only:
      - master
  configuration: Release
  platform: Any CPU
  nuget:
    disable_publish_on_pr: true
  before_build:
    - ps: nuget restore .\Routine.sln
  after_test:
    - ps: .\Tools\NuGet\BuildNugetPackage.ps1

  build:
    project: .\Routine.sln 

  deploy:
    # The following is the details allowing for appveyor to push the 
    # new version of the package to nuget.org.
  - provider: NuGet
    name: production
    api_key: 
      secure: TztsFHaGhIPL2k1ZLIsKg/PACVY7NxAIc8ZQQo20zK3YYj7ZUcdYJ9bsxQRHXOGA
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
  artifacts:
  - path: .\artifacts\**\*.nupkg
    name: Nuget
# configuration for "develop" branch
# build in Release mode and create Nuget pack
-
  branches:
    only:
      - develop
  configuration: Release
  platform: Any CPU
  nuget:
    disable_publish_on_pr: true
  before_build:
    - ps: nuget restore .\Routine.sln
  build:
    project: .\Routine.sln
    verbosity: detailed

# configuration for all other branches except "master" and "develop"
# build in Debug mode and deploy locally for testing
-
  branches:
    except:
      - master
      - develop
  configuration: Release
  platform: Any CPU
  before_build:
    - ps: nuget restore .\Routine.sln
  build:
    project: .\Routine.sln
  after_test:
    - ps: .\Tools\NuGet\BuildNugetPackage.ps1
