-
  image: Visual Studio 2017
# configuration for "master" branch
# build in Release mode and deploy to Nuget
-
  branches:
    only:
      - master
  configuration: Release
  nuget:
    disable_publish_on_pr: true
  install:
    - ps: .\tools\Appveyor\install_dotnet_devpack.ps1
  before_build:
    - dotnet restore .\Routine.sln
    - nuget install NUnit.Runners -Version 3.10.0 -OutputDirectory tools
    - choco install opencover.portable
    - choco install codecov
  build_script:
    - dotnet build .\Routine.sln
  test_script:
    - OpenCover.Console.exe -register:administrator -target:".\tools\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe" -targetargs:".\test\Routine.Test\bin\Release\net48\Routine.Test.dll" -filter:"+[Routine*]* -[*.Test]*" -output:".\routine_coverage.xml"
    - ps: $wc = New-Object 'System.Net.WebClient'
    - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)",(Resolve-Path .\TestResult.xml))
    - codecov -f "routine_coverage.xml"
  after_test:
    - ps: .\src\Routine\Scripts\BuildNugetPackage.ps1

  deploy:
    # The following is the details allowing for appveyor to push the 
    # new version of the package to nuget.org.
  - provider: NuGet
    name: production
    api_key: 
      secure: p0Xytrl8mBwDJ9FHceKWAB4fO927J5GDT2c3UcHXgK3gKKNNGbZaR5HlyM3rnkVo
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
  artifacts:
  - path: .\artifacts\**\*.nupkg
    name: Nuget
# configuration for "develop" branch
# build in Release mode and create Nuget pack
-
  branches:
    only:
      - develop
  configuration: Release
  nuget:
    disable_publish_on_pr: true
  install:
    - ps: .\tools\Appveyor\install_dotnet_devpack.ps1
  before_build:
    - dotnet restore .\Routine.sln
    - nuget install NUnit.Runners -Version 3.10.0 -OutputDirectory tools
    - choco install opencover.portable
    - choco install codecov
  build_script:
    - dotnet build .\Routine.sln
  test_script:
    - OpenCover.Console.exe -register:administrator -target:".\tools\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe" -targetargs:".\test\Routine.Test\bin\Release\net48\Routine.Test.dll" -filter:"+[Routine*]* -[*.Test]*" -output:".\routine_coverage.xml"
    - ps: $wc = New-Object 'System.Net.WebClient'
    - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)",(Resolve-Path .\TestResult.xml))
    - codecov -f "routine_coverage.xml"

# configuration for all other branches except "master" and "develop"
# build in Debug mode and deploy locally for testing
-
  branches:
    except:
      - master
      - develop
  configuration: Release
  install:
    - ps: .\tools\Appveyor\install_dotnet_devpack.ps1
  before_build:
    - dotnet restore .\Routine.sln
    - nuget install NUnit.Runners -Version 3.10.0 -OutputDirectory tools
    - choco install opencover.portable
    - choco install codecov
  build_script:
    - dotnet build .\Routine.sln
  test_script:
    - OpenCover.Console.exe -register:administrator -target:".\tools\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe" -targetargs:".\test\Routine.Test\bin\Release\net48\Routine.Test.dll" -filter:"+[Routine*]* -[*.Test]*" -output:".\routine_coverage.xml"
    - ps: $wc = New-Object 'System.Net.WebClient'
    - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)",(Resolve-Path .\TestResult.xml))
    - codecov -f "routine_coverage.xml"
  after_test:
    - ps: .\src\Routine\Scripts\BuildNugetPackage.ps1

  artifacts:
  - path: .\artifacts\**\*.nupkg
    name: Nuget